version: 2
jobs:
  build:
    docker:
      - image: gfy94/wercker-chromium-node:v0.0.2
    steps:
      - checkout
      - run:
          command: |
            n 6.9.3
            echo "node version is: $(node -v)"
