version: 2
jobs:
  build:
    docker:
      - image: gfy94/wercker-chromium-node:v0.0.2
    steps:
      - checkout
      - run:
          command: |
            n 6.9.3
            echo "node version is: $(node -v)"
      - run:
          command: |
            yarn config set cache-folder $WERCKER_CACHE_DIR/yarn
            HOME=$YARN_CACHE yarn
      - run:
          command: |
            apt-get install git -y
      - run:
          command: |
            npm -v
      - run:
          command: |
            git fetch origin -y
      - run:
          command: |
            git status
      - run:
          command: |
            git merge master
      - run:
          command: |
            npm run lint
